import random
import string
from dataclasses import dataclass, field


def generate_id() -> str:
    """
    Generate a random ID of 15 lowercase letters.
    Returns:
        str: A string of 15 random lowercase letters.
    """
    return "".join(random.choices(string.ascii_lowercase, k=15))


@dataclass
class Student:
    """
    Dataclass representing a student with a name, a surname,
    active status, login, and a unique random ID.
    Attributes:
        name(str): The first name.
        surname(str): The surname.
        active(bool): The status of student, defaults to True.
        login(str): Automatically generated login, with the first
        letter of the student's first name + surname, capitalized.
        id(str): Randomly generated by the generate_id function.
    """
    name: str
    surname: str
    active: bool = True
    login: str = field(init=False)
    id: str = field(init=False)

    def __post_init__(self):
        """
        Post-initialization to generate the login and random ID
        after the student instance is created.
        """
        self.login = (self.name[0] + self.surname).capitalize()
        self.id = generate_id()
